name: deploy-production

on:
  push:
    branches:
      - main
    paths:
      - 'lib/**'

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      S3_BUCKET_ID: prod-us-east-0-jslib-k6-io-website
      CLOUDFRONT_DISTRIBUTION_ID: E2GTCZBXCV8MU0
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        
      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@2f1ddaf3ce1aa677356243d0dd584be33cfa35e3 # get-vault-secrets/v2.1
        with:
          export_env: false
          # arn:.../k6-jslib-uploader-role
          repo_secrets: |
            IAM_ROLE_ARN=deploy:uploader-iam-role

      - name: aws-auth
        uses: grafana/shared-workflows/actions/aws-auth@ed0f3823c0ca0a9e6d5c5681613e53aefd2545e8 # aws-auth/v1.0.5
        with:
          aws-region: 'us-west-1'
          role-arn: '${{ fromJSON(steps.get-secrets.outputs.secrets).IAM_ROLE_ARN }}'
          set-creds-in-environment: true

      - name: Deploy lib to s3
        run: ./deploy.sh
