name: deploy-production

on:
  push:
    branches:
      - main
    paths:
      - 'lib/**'

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      S3_BUCKET_ID: prod-us-east-0-jslib-k6-io-website
      CLOUDFRONT_DISTRIBUTION_ID: E2GTCZBXCV8MU0
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        
      - id: get-secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@e46fe1e9a2bf9e618bcf8d8d32f3a7381b45c06d # get-vault-secrets/v2.0.0
        with:
          export_env: false
          # arn:.../k6-jslib-uploader-role
          repo_secrets: |
            IAM_ROLE_ARN=deploy:uploader-iam-role

      - name: aws-auth
        uses: grafana/shared-workflows/actions/aws-auth@bb04b9b1c3903959957c63d1370b2d49a4b978d0 # aws-auth/v1.0.4
        with:
          aws-region: 'us-west-1'
          role-arn: '${{ fromJSON(steps.get-secrets.outputs.secrets).IAM_ROLE_ARN }}'
          set-creds-in-environment: true

      - name: Deploy lib to s3
        run: ./deploy.sh
